package com.renrenxian.manage.persistence;

import com.renrenxian.manage.model.Jccpush;

public interface JccpushMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jccpush
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    int deleteByPrimaryKey(String uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jccpush
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    int insert(Jccpush record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jccpush
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    int insertSelective(Jccpush record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jccpush
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    Jccpush selectByPrimaryKey(String uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jccpush
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    int updateByPrimaryKeySelective(Jccpush record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jccpush
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    int updateByPrimaryKey(Jccpush record);
}