package com.renrenxian.manage.persistence;

import com.renrenxian.manage.model.Jdan;

public interface JdanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jdan
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jdan
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    int insert(Jdan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jdan
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    int insertSelective(Jdan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jdan
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    Jdan selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jdan
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    int updateByPrimaryKeySelective(Jdan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jdan
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    int updateByPrimaryKey(Jdan record);
}