package com.renrenxian.manage.persistence;

import com.renrenxian.manage.model.Msg;

public interface MsgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    int insert(Msg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    int insertSelective(Msg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    Msg selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    int updateByPrimaryKeySelective(Msg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    int updateByPrimaryKey(Msg record);
}