package com.renrenxian.manage.persistence;

import com.renrenxian.manage.model.SdanChatUser;

public interface SdanChatUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdan_chat_user
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdan_chat_user
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    int insert(SdanChatUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdan_chat_user
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    int insertSelective(SdanChatUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdan_chat_user
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    SdanChatUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdan_chat_user
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    int updateByPrimaryKeySelective(SdanChatUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdan_chat_user
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    int updateByPrimaryKey(SdanChatUser record);
}