package com.renrenxian.manage.persistence;

import com.renrenxian.manage.model.Sdan;

public interface SdanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdan
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdan
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    int insert(Sdan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdan
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    int insertSelective(Sdan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdan
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    Sdan selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdan
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    int updateByPrimaryKeySelective(Sdan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdan
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    int updateByPrimaryKey(Sdan record);
}