package com.renrenxian.manage.persistence;

import com.renrenxian.manage.model.SdanChat;

public interface SdanChatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdan_chat
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdan_chat
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    int insert(SdanChat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdan_chat
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    int insertSelective(SdanChat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdan_chat
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    SdanChat selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdan_chat
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    int updateByPrimaryKeySelective(SdanChat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdan_chat
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    int updateByPrimaryKey(SdanChat record);
}