package com.renrenxian.manage.persistence;

import com.renrenxian.manage.model.Suggest;

public interface SuggestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggest
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggest
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    int insert(Suggest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggest
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    int insertSelective(Suggest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggest
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    Suggest selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggest
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    int updateByPrimaryKeySelective(Suggest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggest
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    int updateByPrimaryKey(Suggest record);
}