package com.renrenxian.manage.persistence;

import com.renrenxian.manage.model.Tousu;

public interface TousuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tousu
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tousu
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    int insert(Tousu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tousu
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    int insertSelective(Tousu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tousu
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    Tousu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tousu
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    int updateByPrimaryKeySelective(Tousu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tousu
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    int updateByPrimaryKey(Tousu record);
}