package com.renrenxian.manage.model;

import java.util.Date;

public class Chat {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat.id
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat.seid
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private Integer seid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat.reid
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private Integer reid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat.regtime
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private Date regtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat.content
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.id
     *
     * @return the value of chat.id
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.id
     *
     * @param id the value for chat.id
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.seid
     *
     * @return the value of chat.seid
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public Integer getSeid() {
        return seid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.seid
     *
     * @param seid the value for chat.seid
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setSeid(Integer seid) {
        this.seid = seid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.reid
     *
     * @return the value of chat.reid
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public Integer getReid() {
        return reid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.reid
     *
     * @param reid the value for chat.reid
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setReid(Integer reid) {
        this.reid = reid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.regtime
     *
     * @return the value of chat.regtime
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public Date getRegtime() {
        return regtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.regtime
     *
     * @param regtime the value for chat.regtime
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setRegtime(Date regtime) {
        this.regtime = regtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.content
     *
     * @return the value of chat.content
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.content
     *
     * @param content the value for chat.content
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setContent(String content) {
        this.content = content;
    }
}