package com.renrenxian.manage.model;

import java.util.Date;

public class ChatUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_user.id
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_user.seid
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private Integer seid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_user.reid
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private Integer reid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_user.regtime
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private Date regtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_user.lastcontent
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String lastcontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_user.u_name
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String uName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_user.kpno
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String kpno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_user.avatar
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String avatar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_user.reu_name
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String reuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_user.rekpno
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String rekpno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_user.reavatar
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String reavatar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_user.hasread
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String hasread;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_user.hehasread
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String hehasread;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_user.id
     *
     * @return the value of chat_user.id
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_user.id
     *
     * @param id the value for chat_user.id
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_user.seid
     *
     * @return the value of chat_user.seid
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public Integer getSeid() {
        return seid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_user.seid
     *
     * @param seid the value for chat_user.seid
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setSeid(Integer seid) {
        this.seid = seid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_user.reid
     *
     * @return the value of chat_user.reid
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public Integer getReid() {
        return reid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_user.reid
     *
     * @param reid the value for chat_user.reid
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setReid(Integer reid) {
        this.reid = reid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_user.regtime
     *
     * @return the value of chat_user.regtime
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public Date getRegtime() {
        return regtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_user.regtime
     *
     * @param regtime the value for chat_user.regtime
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setRegtime(Date regtime) {
        this.regtime = regtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_user.lastcontent
     *
     * @return the value of chat_user.lastcontent
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getLastcontent() {
        return lastcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_user.lastcontent
     *
     * @param lastcontent the value for chat_user.lastcontent
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setLastcontent(String lastcontent) {
        this.lastcontent = lastcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_user.u_name
     *
     * @return the value of chat_user.u_name
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getuName() {
        return uName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_user.u_name
     *
     * @param uName the value for chat_user.u_name
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setuName(String uName) {
        this.uName = uName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_user.kpno
     *
     * @return the value of chat_user.kpno
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getKpno() {
        return kpno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_user.kpno
     *
     * @param kpno the value for chat_user.kpno
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setKpno(String kpno) {
        this.kpno = kpno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_user.avatar
     *
     * @return the value of chat_user.avatar
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_user.avatar
     *
     * @param avatar the value for chat_user.avatar
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_user.reu_name
     *
     * @return the value of chat_user.reu_name
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getReuName() {
        return reuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_user.reu_name
     *
     * @param reuName the value for chat_user.reu_name
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setReuName(String reuName) {
        this.reuName = reuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_user.rekpno
     *
     * @return the value of chat_user.rekpno
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getRekpno() {
        return rekpno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_user.rekpno
     *
     * @param rekpno the value for chat_user.rekpno
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setRekpno(String rekpno) {
        this.rekpno = rekpno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_user.reavatar
     *
     * @return the value of chat_user.reavatar
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getReavatar() {
        return reavatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_user.reavatar
     *
     * @param reavatar the value for chat_user.reavatar
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setReavatar(String reavatar) {
        this.reavatar = reavatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_user.hasread
     *
     * @return the value of chat_user.hasread
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getHasread() {
        return hasread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_user.hasread
     *
     * @param hasread the value for chat_user.hasread
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setHasread(String hasread) {
        this.hasread = hasread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_user.hehasread
     *
     * @return the value of chat_user.hehasread
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getHehasread() {
        return hehasread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_user.hehasread
     *
     * @param hehasread the value for chat_user.hehasread
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setHehasread(String hehasread) {
        this.hehasread = hehasread;
    }
}