package com.renrenxian.manage.model;

import java.util.Date;

public class Info {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.id
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.ver
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String ver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.alert
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String alert;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.locat
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String locat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.aboutkpno
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String aboutkpno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.aboutus
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String aboutus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.regtime
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private Date regtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.androidpath
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String androidpath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.iospath
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String iospath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.user_joinnum
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private Integer userJoinnum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.id
     *
     * @return the value of info.id
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.id
     *
     * @param id the value for info.id
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.ver
     *
     * @return the value of info.ver
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getVer() {
        return ver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.ver
     *
     * @param ver the value for info.ver
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setVer(String ver) {
        this.ver = ver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.alert
     *
     * @return the value of info.alert
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getAlert() {
        return alert;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.alert
     *
     * @param alert the value for info.alert
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setAlert(String alert) {
        this.alert = alert;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.locat
     *
     * @return the value of info.locat
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getLocat() {
        return locat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.locat
     *
     * @param locat the value for info.locat
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setLocat(String locat) {
        this.locat = locat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.aboutkpno
     *
     * @return the value of info.aboutkpno
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getAboutkpno() {
        return aboutkpno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.aboutkpno
     *
     * @param aboutkpno the value for info.aboutkpno
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setAboutkpno(String aboutkpno) {
        this.aboutkpno = aboutkpno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.aboutus
     *
     * @return the value of info.aboutus
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getAboutus() {
        return aboutus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.aboutus
     *
     * @param aboutus the value for info.aboutus
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setAboutus(String aboutus) {
        this.aboutus = aboutus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.regtime
     *
     * @return the value of info.regtime
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public Date getRegtime() {
        return regtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.regtime
     *
     * @param regtime the value for info.regtime
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setRegtime(Date regtime) {
        this.regtime = regtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.androidpath
     *
     * @return the value of info.androidpath
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getAndroidpath() {
        return androidpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.androidpath
     *
     * @param androidpath the value for info.androidpath
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setAndroidpath(String androidpath) {
        this.androidpath = androidpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.iospath
     *
     * @return the value of info.iospath
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getIospath() {
        return iospath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.iospath
     *
     * @param iospath the value for info.iospath
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setIospath(String iospath) {
        this.iospath = iospath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.user_joinnum
     *
     * @return the value of info.user_joinnum
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public Integer getUserJoinnum() {
        return userJoinnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.user_joinnum
     *
     * @param userJoinnum the value for info.user_joinnum
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setUserJoinnum(Integer userJoinnum) {
        this.userJoinnum = userJoinnum;
    }
}