package com.renrenxian.manage.model;

public class Jccpush {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jccpush.uid
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jccpush.pushid
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String pushid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jccpush.device
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String device;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jccpush.uid
     *
     * @return the value of jccpush.uid
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jccpush.uid
     *
     * @param uid the value for jccpush.uid
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setUid(String uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jccpush.pushid
     *
     * @return the value of jccpush.pushid
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getPushid() {
        return pushid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jccpush.pushid
     *
     * @param pushid the value for jccpush.pushid
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setPushid(String pushid) {
        this.pushid = pushid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jccpush.device
     *
     * @return the value of jccpush.device
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getDevice() {
        return device;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jccpush.device
     *
     * @param device the value for jccpush.device
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setDevice(String device) {
        this.device = device;
    }
}