package com.renrenxian.manage.model;

import java.util.Date;

public class Jdan {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdan.id
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdan.jd_id
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private Integer jdId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdan.jd_name
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String jdName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdan.jd_phone
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String jdPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdan.jd_kpno
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String jdKpno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdan.jd_content
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String jdContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdan.jd_regtime
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private Date jdRegtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jdan.id
     *
     * @return the value of jdan.id
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jdan.id
     *
     * @param id the value for jdan.id
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jdan.jd_id
     *
     * @return the value of jdan.jd_id
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public Integer getJdId() {
        return jdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jdan.jd_id
     *
     * @param jdId the value for jdan.jd_id
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setJdId(Integer jdId) {
        this.jdId = jdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jdan.jd_name
     *
     * @return the value of jdan.jd_name
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getJdName() {
        return jdName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jdan.jd_name
     *
     * @param jdName the value for jdan.jd_name
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setJdName(String jdName) {
        this.jdName = jdName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jdan.jd_phone
     *
     * @return the value of jdan.jd_phone
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getJdPhone() {
        return jdPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jdan.jd_phone
     *
     * @param jdPhone the value for jdan.jd_phone
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setJdPhone(String jdPhone) {
        this.jdPhone = jdPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jdan.jd_kpno
     *
     * @return the value of jdan.jd_kpno
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getJdKpno() {
        return jdKpno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jdan.jd_kpno
     *
     * @param jdKpno the value for jdan.jd_kpno
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setJdKpno(String jdKpno) {
        this.jdKpno = jdKpno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jdan.jd_content
     *
     * @return the value of jdan.jd_content
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getJdContent() {
        return jdContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jdan.jd_content
     *
     * @param jdContent the value for jdan.jd_content
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setJdContent(String jdContent) {
        this.jdContent = jdContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jdan.jd_regtime
     *
     * @return the value of jdan.jd_regtime
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public Date getJdRegtime() {
        return jdRegtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jdan.jd_regtime
     *
     * @param jdRegtime the value for jdan.jd_regtime
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setJdRegtime(Date jdRegtime) {
        this.jdRegtime = jdRegtime;
    }
}