package com.renrenxian.manage.model;

import java.util.Date;

public class Party {
	//聚会状态：0代表已完事，黑色
	public final static String STATE_OVER = "0";
	
	//聚会状态：1代表蓝色，可以参加未过期的聚会
	public final static String STATE_ON_JOINING = "1";
	
	//聚会状态：2代表未过期，但是人员已满，无法报名，红色'
	public final static String STATE_ON_UNJOIN = "2";
	
	
    /**
     * 
     */
    private Integer id;

    /**
     * 发起聚会的用户id
     */
    private Integer uid;

    /**
     *发起人姓名
     */
    private String uName;

    /**
     *发起人 电话
     */
    private String phone;

    /**
     * 发起时间
     */
    private Date regtime;

    /**
     * 聚会状态：0代表已完事，黑色，1代表蓝色，可以参加未过期的聚会，2代表未过期，但是人员已满，无法报名，红色
     */
    private String state;

    /**
     * 聚会类型
     */
    private String type;

    /**
     * 聚会时间
     */
    private Date partytime;

    /**
     * 所在城市
     */
    private String city;

    /**
     * 所在区域
     */
    private String area;

    /**
     * 具体地点 （如果不点击报名参加聚会，无法看到该聚会的具体地址）
     */
    private String adr;

    /**
     * 人员上限
     */
    private String membernum;

    /**
     * 已经报名参加人数
     */
    private String joinnum;

    /**
     * 聚会标题
     */
    private String title;

    /**
     * 报名参加者人员列表
     */
    private String content;

    /**
     * 参加人员uid列表，格式“uid1|uid2|uid3”
     */
    private String joinlist;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party.id
     *
     * @return the value of party.id
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party.id
     *
     * @param id the value for party.id
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party.uid
     *
     * @return the value of party.uid
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party.uid
     *
     * @param uid the value for party.uid
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party.u_name
     *
     * @return the value of party.u_name
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getuName() {
        return uName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party.u_name
     *
     * @param uName the value for party.u_name
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setuName(String uName) {
        this.uName = uName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party.phone
     *
     * @return the value of party.phone
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party.phone
     *
     * @param phone the value for party.phone
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party.regtime
     *
     * @return the value of party.regtime
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public Date getRegtime() {
        return regtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party.regtime
     *
     * @param regtime the value for party.regtime
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setRegtime(Date regtime) {
        this.regtime = regtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party.state
     *
     * @return the value of party.state
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party.state
     *
     * @param state the value for party.state
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party.type
     *
     * @return the value of party.type
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party.type
     *
     * @param type the value for party.type
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party.partytime
     *
     * @return the value of party.partytime
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public Date getPartytime() {
        return partytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party.partytime
     *
     * @param partytime the value for party.partytime
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setPartytime(Date partytime) {
        this.partytime = partytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party.city
     *
     * @return the value of party.city
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party.city
     *
     * @param city the value for party.city
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party.area
     *
     * @return the value of party.area
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party.area
     *
     * @param area the value for party.area
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setArea(String area) {
        this.area = area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party.adr
     *
     * @return the value of party.adr
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getAdr() {
        return adr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party.adr
     *
     * @param adr the value for party.adr
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setAdr(String adr) {
        this.adr = adr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party.membernum
     *
     * @return the value of party.membernum
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getMembernum() {
        return membernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party.membernum
     *
     * @param membernum the value for party.membernum
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setMembernum(String membernum) {
        this.membernum = membernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party.joinnum
     *
     * @return the value of party.joinnum
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getJoinnum() {
        return joinnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party.joinnum
     *
     * @param joinnum the value for party.joinnum
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setJoinnum(String joinnum) {
        this.joinnum = joinnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party.title
     *
     * @return the value of party.title
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party.title
     *
     * @param title the value for party.title
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party.content
     *
     * @return the value of party.content
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party.content
     *
     * @param content the value for party.content
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column party.joinlist
     *
     * @return the value of party.joinlist
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getJoinlist() {
        return joinlist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column party.joinlist
     *
     * @param joinlist the value for party.joinlist
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setJoinlist(String joinlist) {
        this.joinlist = joinlist;
    }
}