package com.renrenxian.manage.model;

import java.util.Date;

public class SdanMessage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdan_message.id
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdan_message.sdanid
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String sdanid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdan_message.uid
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdan_message.regtime
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private Date regtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdan_message.message
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String message;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdan_message.u_name
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String uName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdan_message.kpno
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String kpno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdan_message.avatar
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String avatar;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdan_message.id
     *
     * @return the value of sdan_message.id
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdan_message.id
     *
     * @param id the value for sdan_message.id
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdan_message.sdanid
     *
     * @return the value of sdan_message.sdanid
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getSdanid() {
        return sdanid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdan_message.sdanid
     *
     * @param sdanid the value for sdan_message.sdanid
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setSdanid(String sdanid) {
        this.sdanid = sdanid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdan_message.uid
     *
     * @return the value of sdan_message.uid
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdan_message.uid
     *
     * @param uid the value for sdan_message.uid
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setUid(String uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdan_message.regtime
     *
     * @return the value of sdan_message.regtime
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public Date getRegtime() {
        return regtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdan_message.regtime
     *
     * @param regtime the value for sdan_message.regtime
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setRegtime(Date regtime) {
        this.regtime = regtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdan_message.message
     *
     * @return the value of sdan_message.message
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdan_message.message
     *
     * @param message the value for sdan_message.message
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setMessage(String message) {
        this.message = message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdan_message.u_name
     *
     * @return the value of sdan_message.u_name
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getuName() {
        return uName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdan_message.u_name
     *
     * @param uName the value for sdan_message.u_name
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setuName(String uName) {
        this.uName = uName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdan_message.kpno
     *
     * @return the value of sdan_message.kpno
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getKpno() {
        return kpno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdan_message.kpno
     *
     * @param kpno the value for sdan_message.kpno
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setKpno(String kpno) {
        this.kpno = kpno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdan_message.avatar
     *
     * @return the value of sdan_message.avatar
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdan_message.avatar
     *
     * @param avatar the value for sdan_message.avatar
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }
}