package com.renrenxian.manage.model;

import java.util.Date;

public class SdanChat {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdan_chat.id
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdan_chat.sdanid
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String sdanid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdan_chat.seid
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String seid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdan_chat.reid
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String reid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdan_chat.regtime
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private Date regtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdan_chat.message
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String message;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdan_chat.id
     *
     * @return the value of sdan_chat.id
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdan_chat.id
     *
     * @param id the value for sdan_chat.id
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdan_chat.sdanid
     *
     * @return the value of sdan_chat.sdanid
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getSdanid() {
        return sdanid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdan_chat.sdanid
     *
     * @param sdanid the value for sdan_chat.sdanid
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setSdanid(String sdanid) {
        this.sdanid = sdanid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdan_chat.seid
     *
     * @return the value of sdan_chat.seid
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getSeid() {
        return seid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdan_chat.seid
     *
     * @param seid the value for sdan_chat.seid
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setSeid(String seid) {
        this.seid = seid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdan_chat.reid
     *
     * @return the value of sdan_chat.reid
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getReid() {
        return reid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdan_chat.reid
     *
     * @param reid the value for sdan_chat.reid
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setReid(String reid) {
        this.reid = reid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdan_chat.regtime
     *
     * @return the value of sdan_chat.regtime
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public Date getRegtime() {
        return regtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdan_chat.regtime
     *
     * @param regtime the value for sdan_chat.regtime
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setRegtime(Date regtime) {
        this.regtime = regtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdan_chat.message
     *
     * @return the value of sdan_chat.message
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdan_chat.message
     *
     * @param message the value for sdan_chat.message
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setMessage(String message) {
        this.message = message;
    }
}