package com.renrenxian.manage.model;

import java.util.Date;

public class Sdan {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdan.id
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdan.uid
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdan.u_name
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String uName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdan.phone
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdan.regtime
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private Date regtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdan.state
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdan.area
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdan.type
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdan.money
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdan.limitdate
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String limitdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdan.howlong
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String howlong;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdan.title
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdan.assessnum
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String assessnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdan.assesstxt
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String assesstxt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdan.content
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdan.joinlist
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String joinlist;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdan.joinnum
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String joinnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdan.selectid
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String selectid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdan.selectname
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String selectname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdan.selectavatar
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String selectavatar;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdan.id
     *
     * @return the value of sdan.id
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdan.id
     *
     * @param id the value for sdan.id
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdan.uid
     *
     * @return the value of sdan.uid
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdan.uid
     *
     * @param uid the value for sdan.uid
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setUid(String uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdan.u_name
     *
     * @return the value of sdan.u_name
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getuName() {
        return uName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdan.u_name
     *
     * @param uName the value for sdan.u_name
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setuName(String uName) {
        this.uName = uName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdan.phone
     *
     * @return the value of sdan.phone
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdan.phone
     *
     * @param phone the value for sdan.phone
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdan.regtime
     *
     * @return the value of sdan.regtime
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public Date getRegtime() {
        return regtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdan.regtime
     *
     * @param regtime the value for sdan.regtime
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setRegtime(Date regtime) {
        this.regtime = regtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdan.state
     *
     * @return the value of sdan.state
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdan.state
     *
     * @param state the value for sdan.state
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdan.area
     *
     * @return the value of sdan.area
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdan.area
     *
     * @param area the value for sdan.area
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setArea(String area) {
        this.area = area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdan.type
     *
     * @return the value of sdan.type
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdan.type
     *
     * @param type the value for sdan.type
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdan.money
     *
     * @return the value of sdan.money
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdan.money
     *
     * @param money the value for sdan.money
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setMoney(String money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdan.limitdate
     *
     * @return the value of sdan.limitdate
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getLimitdate() {
        return limitdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdan.limitdate
     *
     * @param limitdate the value for sdan.limitdate
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setLimitdate(String limitdate) {
        this.limitdate = limitdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdan.howlong
     *
     * @return the value of sdan.howlong
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getHowlong() {
        return howlong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdan.howlong
     *
     * @param howlong the value for sdan.howlong
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setHowlong(String howlong) {
        this.howlong = howlong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdan.title
     *
     * @return the value of sdan.title
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdan.title
     *
     * @param title the value for sdan.title
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdan.assessnum
     *
     * @return the value of sdan.assessnum
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getAssessnum() {
        return assessnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdan.assessnum
     *
     * @param assessnum the value for sdan.assessnum
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setAssessnum(String assessnum) {
        this.assessnum = assessnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdan.assesstxt
     *
     * @return the value of sdan.assesstxt
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getAssesstxt() {
        return assesstxt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdan.assesstxt
     *
     * @param assesstxt the value for sdan.assesstxt
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setAssesstxt(String assesstxt) {
        this.assesstxt = assesstxt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdan.content
     *
     * @return the value of sdan.content
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdan.content
     *
     * @param content the value for sdan.content
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdan.joinlist
     *
     * @return the value of sdan.joinlist
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getJoinlist() {
        return joinlist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdan.joinlist
     *
     * @param joinlist the value for sdan.joinlist
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setJoinlist(String joinlist) {
        this.joinlist = joinlist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdan.joinnum
     *
     * @return the value of sdan.joinnum
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getJoinnum() {
        return joinnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdan.joinnum
     *
     * @param joinnum the value for sdan.joinnum
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setJoinnum(String joinnum) {
        this.joinnum = joinnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdan.selectid
     *
     * @return the value of sdan.selectid
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getSelectid() {
        return selectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdan.selectid
     *
     * @param selectid the value for sdan.selectid
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setSelectid(String selectid) {
        this.selectid = selectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdan.selectname
     *
     * @return the value of sdan.selectname
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getSelectname() {
        return selectname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdan.selectname
     *
     * @param selectname the value for sdan.selectname
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setSelectname(String selectname) {
        this.selectname = selectname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdan.selectavatar
     *
     * @return the value of sdan.selectavatar
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getSelectavatar() {
        return selectavatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdan.selectavatar
     *
     * @param selectavatar the value for sdan.selectavatar
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setSelectavatar(String selectavatar) {
        this.selectavatar = selectavatar;
    }
}