package com.renrenxian.manage.model;

import java.util.Date;

public class Tousu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tousu.id
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tousu.seid
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String seid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tousu.reid
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String reid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tousu.regtime
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private Date regtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tousu.content
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tousu.type
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tousu.id
     *
     * @return the value of tousu.id
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tousu.id
     *
     * @param id the value for tousu.id
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tousu.seid
     *
     * @return the value of tousu.seid
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getSeid() {
        return seid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tousu.seid
     *
     * @param seid the value for tousu.seid
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setSeid(String seid) {
        this.seid = seid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tousu.reid
     *
     * @return the value of tousu.reid
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getReid() {
        return reid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tousu.reid
     *
     * @param reid the value for tousu.reid
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setReid(String reid) {
        this.reid = reid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tousu.regtime
     *
     * @return the value of tousu.regtime
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public Date getRegtime() {
        return regtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tousu.regtime
     *
     * @param regtime the value for tousu.regtime
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setRegtime(Date regtime) {
        this.regtime = regtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tousu.content
     *
     * @return the value of tousu.content
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tousu.content
     *
     * @param content the value for tousu.content
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tousu.type
     *
     * @return the value of tousu.type
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tousu.type
     *
     * @param type the value for tousu.type
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setType(String type) {
        this.type = type;
    }
}