package com.renrenxian.manage.model;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_name
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String uName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_pwd
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String uPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.regtime
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private Date regtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.phone
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.company
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String company;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.kpno
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private Integer kpno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.address
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.sex
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.old
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String old;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.area
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.keyword
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String keyword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.industy
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String industy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.business
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String business;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.dan_count
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String danCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.year
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.cont
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String cont;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.lnglat
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String lnglat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.followcount
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String followcount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.followmecount
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String followmecount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.followbothcount
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String followbothcount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.follow_list
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String followList;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.avatar
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String avatar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.logtime
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private Date logtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.lng
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String lng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.lat
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String lat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.alert
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String alert;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.locat
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String locat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.alert2
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String alert2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_name
     *
     * @return the value of user.u_name
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getuName() {
        return uName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_name
     *
     * @param uName the value for user.u_name
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setuName(String uName) {
        this.uName = uName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_pwd
     *
     * @return the value of user.u_pwd
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getuPwd() {
        return uPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_pwd
     *
     * @param uPwd the value for user.u_pwd
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setuPwd(String uPwd) {
        this.uPwd = uPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.regtime
     *
     * @return the value of user.regtime
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public Date getRegtime() {
        return regtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.regtime
     *
     * @param regtime the value for user.regtime
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setRegtime(Date regtime) {
        this.regtime = regtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.phone
     *
     * @return the value of user.phone
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.phone
     *
     * @param phone the value for user.phone
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.company
     *
     * @return the value of user.company
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.company
     *
     * @param company the value for user.company
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setCompany(String company) {
        this.company = company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.kpno
     *
     * @return the value of user.kpno
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public Integer getKpno() {
        return kpno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.kpno
     *
     * @param kpno the value for user.kpno
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setKpno(Integer kpno) {
        this.kpno = kpno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.address
     *
     * @return the value of user.address
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.address
     *
     * @param address the value for user.address
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.sex
     *
     * @return the value of user.sex
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.sex
     *
     * @param sex the value for user.sex
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.old
     *
     * @return the value of user.old
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getOld() {
        return old;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.old
     *
     * @param old the value for user.old
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setOld(String old) {
        this.old = old;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.area
     *
     * @return the value of user.area
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.area
     *
     * @param area the value for user.area
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setArea(String area) {
        this.area = area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.keyword
     *
     * @return the value of user.keyword
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.keyword
     *
     * @param keyword the value for user.keyword
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.industy
     *
     * @return the value of user.industy
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getIndusty() {
        return industy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.industy
     *
     * @param industy the value for user.industy
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setIndusty(String industy) {
        this.industy = industy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.business
     *
     * @return the value of user.business
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getBusiness() {
        return business;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.business
     *
     * @param business the value for user.business
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setBusiness(String business) {
        this.business = business;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.dan_count
     *
     * @return the value of user.dan_count
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getDanCount() {
        return danCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.dan_count
     *
     * @param danCount the value for user.dan_count
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setDanCount(String danCount) {
        this.danCount = danCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.year
     *
     * @return the value of user.year
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.year
     *
     * @param year the value for user.year
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setYear(String year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.cont
     *
     * @return the value of user.cont
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getCont() {
        return cont;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.cont
     *
     * @param cont the value for user.cont
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setCont(String cont) {
        this.cont = cont;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.lnglat
     *
     * @return the value of user.lnglat
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getLnglat() {
        return lnglat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.lnglat
     *
     * @param lnglat the value for user.lnglat
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setLnglat(String lnglat) {
        this.lnglat = lnglat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.followcount
     *
     * @return the value of user.followcount
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getFollowcount() {
        return followcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.followcount
     *
     * @param followcount the value for user.followcount
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setFollowcount(String followcount) {
        this.followcount = followcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.followmecount
     *
     * @return the value of user.followmecount
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getFollowmecount() {
        return followmecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.followmecount
     *
     * @param followmecount the value for user.followmecount
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setFollowmecount(String followmecount) {
        this.followmecount = followmecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.followbothcount
     *
     * @return the value of user.followbothcount
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getFollowbothcount() {
        return followbothcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.followbothcount
     *
     * @param followbothcount the value for user.followbothcount
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setFollowbothcount(String followbothcount) {
        this.followbothcount = followbothcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.follow_list
     *
     * @return the value of user.follow_list
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getFollowList() {
        return followList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.follow_list
     *
     * @param followList the value for user.follow_list
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setFollowList(String followList) {
        this.followList = followList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.avatar
     *
     * @return the value of user.avatar
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.avatar
     *
     * @param avatar the value for user.avatar
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.logtime
     *
     * @return the value of user.logtime
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public Date getLogtime() {
        return logtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.logtime
     *
     * @param logtime the value for user.logtime
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setLogtime(Date logtime) {
        this.logtime = logtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.lng
     *
     * @return the value of user.lng
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getLng() {
        return lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.lng
     *
     * @param lng the value for user.lng
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setLng(String lng) {
        this.lng = lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.lat
     *
     * @return the value of user.lat
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.lat
     *
     * @param lat the value for user.lat
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setLat(String lat) {
        this.lat = lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.alert
     *
     * @return the value of user.alert
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getAlert() {
        return alert;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.alert
     *
     * @param alert the value for user.alert
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setAlert(String alert) {
        this.alert = alert;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.locat
     *
     * @return the value of user.locat
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getLocat() {
        return locat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.locat
     *
     * @param locat the value for user.locat
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setLocat(String locat) {
        this.locat = locat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.alert2
     *
     * @return the value of user.alert2
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getAlert2() {
        return alert2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.alert2
     *
     * @param alert2 the value for user.alert2
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setAlert2(String alert2) {
        this.alert2 = alert2;
    }
}