package com.renrenxian.manage.model;

import java.util.Date;

public class Yzm {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yzm.id
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yzm.phone
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yzm.yzm
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private String yzm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yzm.regtime
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    private Date regtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yzm.id
     *
     * @return the value of yzm.id
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yzm.id
     *
     * @param id the value for yzm.id
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yzm.phone
     *
     * @return the value of yzm.phone
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yzm.phone
     *
     * @param phone the value for yzm.phone
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yzm.yzm
     *
     * @return the value of yzm.yzm
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public String getYzm() {
        return yzm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yzm.yzm
     *
     * @param yzm the value for yzm.yzm
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setYzm(String yzm) {
        this.yzm = yzm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yzm.regtime
     *
     * @return the value of yzm.regtime
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public Date getRegtime() {
        return regtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yzm.regtime
     *
     * @param regtime the value for yzm.regtime
     *
     * @mbggenerated Thu Oct 30 00:39:34 CST 2014
     */
    public void setRegtime(Date regtime) {
        this.regtime = regtime;
    }
}